apiVersion: v1
kind: Service
metadata:
  name: newsletter-sign-up-with-success-message-main
  namespace: default
spec:
  selector:
    app: newsletter-sign-up-with-success-message-main-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
